#!/usr/bin/env python3
"""
Oracle 数据库查询优化示例：EXISTS 子查询中的 OR 条件优化

这个脚本演示了如何在 Oracle 数据库上通过重写 EXISTS 子查询中的 OR 条件来优化查询性能。
Oracle 的查询重写引擎已经内置了部分优化，但手动重写仍然可以获得额外的性能提升。

作者: AI Assistant
日期: 2024
"""

import cx_Oracle
import json
import time
from datetime import datetime
from typing import Dict, List, Tuple, Optional
import getpass


class OracleQueryOptimizer:
    """Oracle 查询优化器测试类"""
    
    def __init__(self, host: str = '172.23.160.1', port: int = 1521, 
                 service_name: str = 'XEPDB1', user: str = 'sys', password: str = '111111'):
        """初始化 Oracle 连接参数"""
        self.host = host
        self.port = port
        self.service_name = service_name
        self.user = user
        self.password = password
        self.connection = None
    
    def connect(self) -> bool:
        """连接 Oracle 数据库"""
        try:
            dsn = cx_Oracle.makedsn(self.host, self.port, service_name=self.service_name)
            self.connection = cx_Oracle.connect(self.user, self.password, dsn, mode=cx_Oracle.SYSDBA)
            print("✅ Oracle 连接成功")
            return True
        except Exception as e:
            print(f"❌ Oracle 连接失败: {e}")
            return False
    
    def execute_sql(self, sql: str, fetch_all: bool = True) -> Tuple[bool, List, str]:
        """执行 SQL 语句并返回结果"""
        if not self.connection:
            return False, [], "未连接到数据库"
        
        cursor = self.connection.cursor()
        try:
            cursor.execute(sql)
            if fetch_all:
                rows = cursor.fetchall()
                return True, rows, ""
            else:
                return True, [], ""
        except Exception as e:
            return False, [], str(e)
        finally:
            cursor.close()
    
    def create_test_environment(self, table_size: int = 10000) -> bool:
        """创建测试环境和数据"""
        print(f"创建测试环境 (表大小: {table_size:,} 行)...")
        
        # 清理现有表
        cleanup_sqls = [
            "BEGIN EXECUTE IMMEDIATE 'DROP TABLE customers CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;",
            "BEGIN EXECUTE IMMEDIATE 'DROP TABLE orders CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;",
            "BEGIN EXECUTE IMMEDIATE 'DROP TABLE products CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;"
        ]
        
        for cleanup_sql in cleanup_sqls:
            success, _, error = self.execute_sql(cleanup_sql, fetch_all=False)
            if not success:
                print(f"清理表失败: {error}")
                return False
        
        # 创建测试表
        create_sqls = [
            # 创建客户表
            """
            CREATE TABLE customers (
                customer_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                name VARCHAR2(100),
                email VARCHAR2(100),
                phone VARCHAR2(20),
                region VARCHAR2(50),
                created_date DATE
            )
            """,
            # 创建产品表
            """
            CREATE TABLE products (
                product_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                name VARCHAR2(100),
                category VARCHAR2(50),
                price NUMBER(10,2),
                stock_quantity NUMBER
            )
            """,
            # 创建订单表
            """
            CREATE TABLE orders (
                order_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                customer_id NUMBER,
                product_id NUMBER,
                quantity NUMBER,
                order_date DATE,
                status VARCHAR2(20)
            )
            """,
            # 插入客户数据
            f"""
            INSERT INTO customers (name, email, phone, region, created_date)
            SELECT 
                'Customer_' || LEVEL,
                'customer' || LEVEL || '@example.com',
                '555-' || LPAD(ROUND(DBMS_RANDOM.VALUE(1000, 9999)), 4, '0'),
                CASE ROUND(DBMS_RANDOM.VALUE(1, 4))
                    WHEN 1 THEN 'North'
                    WHEN 2 THEN 'South' 
                    WHEN 3 THEN 'East'
                    ELSE 'West'
                END,
                SYSDATE - ROUND(DBMS_RANDOM.VALUE(1, 365))
            FROM DUAL
            CONNECT BY LEVEL <= {table_size}
            """,
            # 插入产品数据
            f"""
            INSERT INTO products (name, category, price, stock_quantity)
            SELECT 
                'Product_' || LEVEL,
                CASE ROUND(DBMS_RANDOM.VALUE(1, 5))
                    WHEN 1 THEN 'Electronics'
                    WHEN 2 THEN 'Clothing'
                    WHEN 3 THEN 'Books'
                    WHEN 4 THEN 'Home'
                    ELSE 'Sports'
                END,
                ROUND(DBMS_RANDOM.VALUE(10, 1000), 2),
                ROUND(DBMS_RANDOM.VALUE(0, 1000))
            FROM DUAL
            CONNECT BY LEVEL <= {table_size}
            """,
            # 插入订单数据
            f"""
            INSERT INTO orders (customer_id, product_id, quantity, order_date, status)
            SELECT 
                ROUND(DBMS_RANDOM.VALUE(1, {table_size})),
                ROUND(DBMS_RANDOM.VALUE(1, {table_size})),
                ROUND(DBMS_RANDOM.VALUE(1, 10)),
                SYSDATE - ROUND(DBMS_RANDOM.VALUE(1, 365)),
                CASE ROUND(DBMS_RANDOM.VALUE(1, 3))
                    WHEN 1 THEN 'pending'
                    WHEN 2 THEN 'shipped'
                    ELSE 'delivered'
                END
            FROM DUAL
            CONNECT BY LEVEL <= {table_size * 2}
            """,
            # 创建索引
            "CREATE INDEX idx_customers_region ON customers(region)",
            "CREATE INDEX idx_customers_email ON customers(email)",
            "CREATE INDEX idx_products_category ON products(category)",
            "CREATE INDEX idx_products_price ON products(price)",
            "CREATE INDEX idx_orders_customer_id ON orders(customer_id)",
            "CREATE INDEX idx_orders_product_id ON orders(product_id)",
            "CREATE INDEX idx_orders_date ON orders(order_date)",
            # 更新统计信息
            "BEGIN DBMS_STATS.GATHER_TABLE_STATS(USER, 'CUSTOMERS'); END;",
            "BEGIN DBMS_STATS.GATHER_TABLE_STATS(USER, 'PRODUCTS'); END;",
            "BEGIN DBMS_STATS.GATHER_TABLE_STATS(USER, 'ORDERS'); END;",
            "COMMIT"
        ]
        
        for i, create_sql in enumerate(create_sqls):
            success, _, error = self.execute_sql(create_sql, fetch_all=False)
            if not success:
                print(f"创建测试环境失败 (步骤 {i+1}): {error}")
                return False
        
        print("✅ 测试环境创建成功")
        return True
    
    def get_execution_plan(self, sql: str, query_name: str) -> Dict:
        """获取执行计划"""
        print(f"\n分析查询: {query_name}")
        print("-" * 60)
        
        # 启用执行计划收集
        self.execute_sql("ALTER SESSION SET STATISTICS_LEVEL = ALL", fetch_all=False)
        
        # 执行查询
        start_time = time.time()
        success, rows, error = self.execute_sql(sql)
        execution_time = (time.time() - start_time) * 1000  # 转换为毫秒
        
        if not success:
            print(f"❌ 查询执行失败: {error}")
            return {}
        
        # 获取执行计划
        plan_sql = """
        SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY_CURSOR(NULL, NULL, 'ALLSTATS LAST'))
        """
        
        success, plan_rows, error = self.execute_sql(plan_sql)
        if not success:
            print(f"❌ 获取执行计划失败: {error}")
            return {}
        
        # 分析执行计划
        plan_text = '\n'.join([row[0] for row in plan_rows])
        print("执行计划:")
        print(plan_text)
        
        # 提取关键信息
        analysis = {
            'query_name': query_name,
            'execution_time_ms': execution_time,
            'rows_returned': len(rows),
            'plan_text': plan_text,
            'has_nested_loop': 'NESTED LOOPS' in plan_text.upper(),
            'has_hash_join': 'HASH JOIN' in plan_text.upper(),
            'has_index_scan': 'INDEX' in plan_text.upper(),
            'has_table_scan': 'TABLE ACCESS FULL' in plan_text.upper(),
            'has_union_all': 'UNION-ALL' in plan_text.upper(),
            'has_or_expansion': 'VW_ORE_' in plan_text.upper()
        }
        
        print(f"执行时间: {analysis['execution_time_ms']:.2f} ms")
        print(f"返回行数: {analysis['rows_returned']:,}")
        print(f"包含嵌套循环: {analysis['has_nested_loop']}")
        print(f"包含哈希连接: {analysis['has_hash_join']}")
        print(f"包含索引扫描: {analysis['has_index_scan']}")
        print(f"包含全表扫描: {analysis['has_table_scan']}")
        print(f"包含 UNION-ALL: {analysis['has_union_all']}")
        print(f"包含 OR 扩展: {analysis['has_or_expansion']}")
        
        return analysis
    
    def run_optimization_comparison(self) -> Dict:
        """运行优化对比测试"""
        print("\n" + "="*80)
        print("Oracle 查询优化对比测试")
        print("="*80)
        
        # 定义测试查询
        queries = {
            "原始查询 (OR 条件在 EXISTS 中)": """
                SELECT c.customer_id, c.name, c.email
                FROM customers c
                WHERE EXISTS (
                    SELECT 1 FROM orders o 
                    JOIN products p ON o.product_id = p.product_id
                    WHERE o.customer_id = c.customer_id 
                    AND (p.category = 'Electronics' OR p.price > 500)
                )
            """,
            
            "优化查询 (OR 条件分解)": """
                SELECT c.customer_id, c.name, c.email
                FROM customers c
                WHERE EXISTS (
                    SELECT 1 FROM orders o 
                    JOIN products p ON o.product_id = p.product_id
                    WHERE o.customer_id = c.customer_id 
                    AND p.category = 'Electronics'
                )
                OR EXISTS (
                    SELECT 1 FROM orders o 
                    JOIN products p ON o.product_id = p.product_id
                    WHERE o.customer_id = c.customer_id 
                    AND p.price > 500
                )
            """,
            
            "使用提示的优化查询": """
                SELECT /*+ USE_HASH(c, o, p) */ c.customer_id, c.name, c.email
                FROM customers c
                WHERE EXISTS (
                    SELECT 1 FROM orders o 
                    JOIN products p ON o.product_id = p.product_id
                    WHERE o.customer_id = c.customer_id 
                    AND (p.category = 'Electronics' OR p.price > 500)
                )
            """,
            
            "进一步优化 (使用 UNION)": """
                SELECT DISTINCT c.customer_id, c.name, c.email
                FROM customers c
                WHERE c.customer_id IN (
                    SELECT o.customer_id FROM orders o 
                    JOIN products p ON o.product_id = p.product_id
                    WHERE p.category = 'Electronics'
                    UNION
                    SELECT o.customer_id FROM orders o 
                    JOIN products p ON o.product_id = p.product_id
                    WHERE p.price > 500
                )
            """
        }
        
        results = {}
        
        for query_name, sql in queries.items():
            results[query_name] = self.get_execution_plan(sql, query_name)
            time.sleep(1)  # 避免缓存影响
        
        return results
    
    def analyze_results(self, results: Dict) -> None:
        """分析并展示优化结果"""
        print("\n" + "="*80)
        print("Oracle 优化结果分析")
        print("="*80)
        
        if not results:
            print("❌ 没有可分析的结果")
            return
        
        # 提取执行时间进行对比
        execution_times = {}
        join_types = {}
        
        for query_name, analysis in results.items():
            if analysis:
                execution_times[query_name] = analysis['execution_time_ms']
                join_types[query_name] = {
                    'nested_loop': analysis['has_nested_loop'],
                    'hash_join': analysis['has_hash_join'],
                    'index_scan': analysis['has_index_scan'],
                    'table_scan': analysis['has_table_scan'],
                    'union_all': analysis['has_union_all'],
                    'or_expansion': analysis['has_or_expansion']
                }
        
        if len(execution_times) < 2:
            print("❌ 结果不足，无法进行对比分析")
            return
        
        # 性能对比
        print("\n📊 性能对比:")
        print("-" * 80)
        print(f"{'查询类型':<30} {'执行时间(ms)':<15} {'返回行数':<10}")
        print("-" * 80)
        
        for query_name, analysis in results.items():
            if analysis:
                print(f"{query_name:<30} {analysis['execution_time_ms']:<15.2f} {analysis['rows_returned']:<10}")
        
        # 计算性能提升
        if len(execution_times) >= 2:
            original_time = list(execution_times.values())[0]
            optimized_time = list(execution_times.values())[1]
            improvement = (original_time - optimized_time) / original_time * 100 if original_time > 0 else 0
            
            print(f"\n🚀 性能提升: {improvement:.1f}%")
            print(f"   原始查询: {original_time:.2f} ms")
            print(f"   优化查询: {optimized_time:.2f} ms")
        
        # 连接类型对比
        print("\n🔗 连接类型对比:")
        print("-" * 80)
        for query_name, join_info in join_types.items():
            print(f"{query_name}:")
            print(f"  嵌套循环: {join_info['nested_loop']}")
            print(f"  哈希连接: {join_info['hash_join']}")
            print(f"  索引扫描: {join_info['index_scan']}")
            print(f"  全表扫描: {join_info['table_scan']}")
            print(f"  UNION-ALL: {join_info['union_all']}")
            print(f"  OR 扩展: {join_info['or_expansion']}")
            print()
        
        # Oracle 特定优化建议
        print("\n💡 Oracle 特定优化建议:")
        print("-" * 60)
        print("1. Oracle 的查询重写引擎 (Query Rewrite Engine) 已自动优化 OR 条件")
        print("2. 使用 Oracle 的提示 (Hints) 来指导优化器选择执行计划")
        print("3. 利用 Oracle 的统计信息收集 (DBMS_STATS) 获得准确的成本估算")
        print("4. 考虑使用 Oracle 的物化视图来预计算复杂查询")
        print("5. 使用 Oracle 的分区表功能处理大数据集")
        print("6. 利用 Oracle 的并行查询功能提升性能")
        print("7. 使用 Oracle 的索引提示来强制使用特定索引")
        print("8. 考虑使用 Oracle 的结果集缓存 (Result Cache)")
    
    def test_oracle_specific_features(self) -> None:
        """测试 Oracle 特定功能"""
        print("\n" + "="*80)
        print("Oracle 特定功能测试")
        print("="*80)
        
        # 测试不同的提示
        hint_tests = {
            "使用 USE_HASH 提示": """
                SELECT /*+ USE_HASH(c, o, p) */ c.customer_id, c.name
                FROM customers c
                WHERE EXISTS (
                    SELECT 1 FROM orders o 
                    JOIN products p ON o.product_id = p.product_id
                    WHERE o.customer_id = c.customer_id 
                    AND (p.category = 'Electronics' OR p.price > 500)
                )
            """,
            "使用 USE_NL 提示": """
                SELECT /*+ USE_NL(c, o, p) */ c.customer_id, c.name
                FROM customers c
                WHERE EXISTS (
                    SELECT 1 FROM orders o 
                    JOIN products p ON o.product_id = p.product_id
                    WHERE o.customer_id = c.customer_id 
                    AND (p.category = 'Electronics' OR p.price > 500)
                )
            """,
            "使用 INDEX 提示": """
                SELECT /*+ INDEX(p idx_products_category) */ c.customer_id, c.name
                FROM customers c
                WHERE EXISTS (
                    SELECT 1 FROM orders o 
                    JOIN products p ON o.product_id = p.product_id
                    WHERE o.customer_id = c.customer_id 
                    AND (p.category = 'Electronics' OR p.price > 500)
                )
            """,
            "使用 PARALLEL 提示": """
                SELECT /*+ PARALLEL(c, 4) */ c.customer_id, c.name
                FROM customers c
                WHERE EXISTS (
                    SELECT 1 FROM orders o 
                    JOIN products p ON o.product_id = p.product_id
                    WHERE o.customer_id = c.customer_id 
                    AND (p.category = 'Electronics' OR p.price > 500)
                )
            """
        }
        
        for query_name, sql in hint_tests.items():
            self.get_execution_plan(sql, query_name)
            time.sleep(1)
    
    def cleanup(self) -> None:
        """清理测试环境"""
        print("\n清理测试环境...")
        cleanup_sqls = [
            "BEGIN EXECUTE IMMEDIATE 'DROP TABLE customers CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;",
            "BEGIN EXECUTE IMMEDIATE 'DROP TABLE orders CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;",
            "BEGIN EXECUTE IMMEDIATE 'DROP TABLE products CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;"
        ]
        
        for cleanup_sql in cleanup_sqls:
            success, _, error = self.execute_sql(cleanup_sql, fetch_all=False)
            if not success:
                print(f"⚠️ 清理时出现警告: {error}")
        
        print("✅ 测试环境清理完成")
    
    def close(self) -> None:
        """关闭数据库连接"""
        if self.connection:
            self.connection.close()
            print("Oracle 连接已关闭")


def main():
    """主函数"""
    print("Oracle 数据库查询优化示例")
    print("演示 EXISTS 子查询中 OR 条件的优化方法")
    print("="*80)
    
    # 创建优化器实例
    optimizer = OracleQueryOptimizer()
    
    try:
        # 连接数据库
        if not optimizer.connect():
            print("❌ 无法连接到 Oracle 数据库，退出")
            return 1
        
        # 创建测试环境
        if not optimizer.create_test_environment(table_size=5000):
            print("❌ 无法创建测试环境，退出")
            return 1
        
        # 运行优化对比测试
        results = optimizer.run_optimization_comparison()
        
        # 分析结果
        optimizer.analyze_results(results)
        
        # 测试 Oracle 特定功能
        optimizer.test_oracle_specific_features()
        
        print("\n✅ Oracle 优化示例完成!")
        
    except KeyboardInterrupt:
        print("\n⚠️ 测试被用户中断")
    except Exception as e:
        print(f"\n❌ 测试过程中出现错误: {e}")
        return 1
    finally:
        # 清理测试环境
        optimizer.cleanup()
        optimizer.close()
    
    return 0


if __name__ == '__main__':
    import sys
    sys.exit(main())
